<?php

echo '<div style="height:60px"></div>' . "\n" . '<div id="add_user_form" style="display:none">' . "\n" . '  <form action="';
echo url('admin/user.add_post');
echo '" id="form_v" method="post">' . "\n" . '    <div class="txt-fld">' . "\n" . '      <label for="" class="tit">用户角色</label>' . "\n" . '      <input type="radio" name="type" value="1"  checked="checked">' . "\n" . '      网站主' . "\n" . '      <input type="radio" name="type" value="2" >' . "\n" . '      广告商' . "\n" . '      <input type="radio" name="type" value="3" >' . "\n" . '      联盟客服' . "\n" . '      <input type="radio" name="type" value="4" >' . "\n" . '      联盟商务 </div>' . "\n" . '    <div class="txt-fld">' . "\n" . '      <label for=""  class="tit">用户名</label>' . "\n" . '      <input id="username_ajax" name="username" type="text">' . "\n" . '    </div>' . "\n" . '    <div class="txt-fld">' . "\n" . '      <label for=""  class="tit">用户密码</label>' . "\n" . '      <input id="" name="password" type="text">' . "\n" . '    </div>' . "\n\t\n\t" . ' ' . "\n\t\n" . '    <div class="txt-fld">' . "\n" . '      <label for=""  class="tit">联系人</label>' . "\n" . '      <input id="" name="contact" type="text">' . "\n" . '    </div>' . "\n" . '    <div class="txt-fld">' . "\n" . '      <label for=""  class="tit">QQ</label>' . "\n" . '      <input id="" name="qq" type="text">' . "\n" . '    </div>' . "\n" . '    <div class="btn-fld">' . "\n" . '      <button type="submit">提交 »</button>' . "\n" . '    </div>' . "\n" . '  </form>' . "\n" . '</div>' . "\n\n" . '<div class="ipnum" style="position: absolute;top: 45px;background-color: #CC4444;padding: 3px;color: #fff; padding-left: 10px;padding-right: 10px;max-height: 20px; max-width: 210px;">30分钟结算: <span id=\'horusum\'>统计中...</span> 次</div>' . "\n\n\n" . '<a href="javascript:void(0)" class="sidebar_switch on_switch" title="隐藏左侧">隐藏</a>' . "\n" . '<script language="JavaScript" type="text/javascript">' . "\n\n\n" . 'function horus(){ ' . "\n" . '      $.get("';
echo url('admin/ip.get_list?horusum=y');
echo '",null,function callback(data){$("#horusum").html(data);});' . "\n" . '      t=setTimeout("horus()",8000)' . "\n" . '}' . "\n" . 'horus();' . "\n\n" . ' ' . "\n" . '//导航子菜单' . "\t\t\t\n\t\t\t\n" . ' ' . "\n" . '$(\'.dropdown\').on(\'mouseenter\', function(option) { ' . "\n\t" . '$(\'.dropdown-menu,.tpm\').css(\'display\',\'none\'); ' . "\n\t" . '$(this).find(\'.dropdown-menu,.tpm\').css(\'display\',\'block\');' . "\n" . '});' . "\n\n" . '$(\'.dropdown-menu\').on(\'mouseleave\', function(option) { ' . "\n\t" . '$(\'.dropdown-menu,.tpm\').css(\'display\',\'none\'); ' . "\n" . '});' . "\n\n\n\n" . '//导航菜单点其它关闭' . "\t\t\t\n" . '$(\'body\').click(function(evt) {' . "\n" . ' ' . "\t\t" . '$(\'.alert\').hide("slow");' . "\n\t\t" . 'if($(evt.target).parents(".nav_m").length==0){' . "\n" . ' ' . "\t\t\t" . '$(\'.dropdown-menu,.tpm\').css(\'display\',\'none\'); ' . "\n\t\t" . '}' . "\n\t\t" . '//$(".popover").css(\'top\',\'-1000px\'); ' . "\n" . '});' . "\n\t\n\n\n" . 'function err(text){' . "\n\t" . 'var h = \'<div class="alert err"><!-- <a class="close" href="javascript:;">×</a>--><strong>\'+text+\'.</strong> </div>\';' . "\n\t" . ' $("body").append(h);' . "\n" . '}' . "\n\n" . '$(".add_user").click(function(){' . "\n\t" . 'box.form("#add_user_form","新建用户");' . "\n\t" . 'remote_url = "';
echo url('admin/user.remote_user');
echo '";' . "\n\t" . 'add_user_vlt.init();' . "\n" . '});' . "\n\n" . '$(".on_switch").click(function(){' . "\n\t" . ' if($("#sidebar").is(":hidden")){' . "\n\t\t" . '$("#sidebar").show();' . "\n\t" . ' ' . "\t" . '$(\'#main-content\').css(\'marginLeft\', \'230px\');' . "\n\t" . ' ' . "\t" . '$("body").css("backgroundImage","url(\'';
echo SRC_TPL_DIR;
echo '/images/main_bg.gif\')");' . "\n\t" . ' ' . "\t" . '$(this).css(\'left\', \'180px\');' . "\n\t" . ' }else{' . "\n\t" . ' ' . "\t" . '$("#sidebar").hide();' . "\n\t" . ' ' . "\t" . '$(\'#main-content\').css(\'marginLeft\', \'30px\');' . "\n\t" . ' ' . "\t" . '$("body").css("backgroundImage","url(\'\')");' . "\n\t" . ' ' . "\t" . '$(this).css(\'left\', \'5px\');' . "\n\t" . ' }' . "\n" . '});' . "\n\n\n" . '</script>' . "\n\n\n\n";
zy_updata();

?>
